### ISSUE TITLE
Skeleton Initialization files to ES Module format

### ISSUE THREAD

**Issue by michael-russo** [ramipellumbi/FASTRAQ#1]
Hi,

Love the branch, only issue I had when I forked was the `babel.config.js` and `jest.config.js` files. The exports should be as an `ES module`, rather than a `CommonJS module`.

**Comment by ramipellumbi** [comment]
Fixed! https://github.com/ramipellumbi/NodeJS-Server-Template/commit/7abdcf83271a2fe27343f4a18dc831d22f3d9ecf
